[package]
name = "vdt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl = "0.19"
anyhow = "1.0"
rand = "0.8"
image = "0.24"
arena_system = "0.0.4"